### PR TITLE
Make request.source nullable because it is optional in the openrtb spec

### PR DESCRIPTION
**Pull request by rishisharan72**
Context: https://sincere-corporation.slack.com/archives/C060949DQFJ/p1699375480583839

### CODE REVIEW

**Review by skinandbones — COMMENTED** [review]
1. This appears to be a dupe of https://github.com/adsbynimbus/nimbus-openrtb/pull/134. 
 Do we know the story on that?
2. Can this regression be traced back to a change on the date in question?
3. Is there relevant test coverage?

**Comment by rishisharan72** [comment]
1) We do not know the story on Dmitry's PR but I will reach out via Slack
2) Yes, this change was [included in the change on Oct 24](https://github.com/timehop/apicard/pull/1740/files#diff-33ef32bf6c23acb95f5902d7097b7a1d5128ca061167ec0716715b0b9eeaa5f6L46) and here is the [change to that package](https://github.com/timehop/nimbus-openrtb/compare/4881cc66d1f9d415865e336bdaf71ef24aa12bd8...timehop:nimbus-openrtb:f7db7feca67479a53feb8263d11608b3fd71b2e4)
3) I will add one to this PR, there is no current relevant test coverage

**Review by skinandbones — APPROVED** [review]
This reverts a change that was introduced on the regression date.   🚬 🔫

**Comment by skinandbones** [comment]
@rishisharan72 it's not clear to me if we should be using our own fork of this repo or the adsbynimbus version.   Let's get some clarity on the issue.

**Comment by rishisharan72** [comment]
From Dmitry:

> Marc believed that other publishers were using this repo on their proxy servers - some of our oldest pubs - and he didnt want to introduce a breaking change, but also didn't want a major version bump until some of the other fields were addresses like this one. I wanted to move forward with apicard getting the benefit of the change

> Your own fork would be best. Same as we advised to other external clients. Most followed that advice. It seems others did not

**Comment by rishisharan72** [comment]
Side note, there really isn't a way to test to avoid this. The function was working exactly as intended, the contract itself was broken.

**Pull request merged**
